### ISSUE TITLE
suppress bibliography horizontal dotted line ? 

### ISSUE THREAD

**Issue by gvoysey** [fernandomayer/moderncv#1]
I'd like to have my publications with the same styling as `\Section{}`. 

Currently, i have

```
\begin{samepage}
\renewcommand{\refname}{Selected Publications}
\nocite{*}
\bibliographystyle{abbrv}
\bibliography{pubs}                        
\vspace{1em}
\end{samepage}

```

which styles it differently. 

Changing this to 

```
\begin{samepage}
\section{Selected Publications}
\renewcommand{\refname}{}
\nocite{*}
\bibliographystyle{abbrv}
\bibliography{pubs}                        
\vspace{1em}
\end{samepage}
```

generates a residual and spurious horizontal dotted line below, as seen in this image. 
![screen shot 2015-01-24 at 18 16 50](https://cloud.githubusercontent.com/assets/3641839/5889444/3919ccfc-a3f5-11e4-9e6e-a9ca679fe654.png)

How should i prevent this?

**Comment by fernandomayer** [comment]
Please, can you provide some more information? Are you using something different from the template's preamble?

I can't reproduce this error. Within the template, your second snippet of code works like expected:

![snip](https://cloud.githubusercontent.com/assets/650253/6120595/fe28d6a2-b0be-11e4-9e60-496f84ea132f.png)

If you provide some reproducible code I can take a look on what's happening.

Thanks.

**Comment by gvoysey** [comment]
[Here](https://gist.github.com/gvoysey/0fbaad6786a4b2febb8c)  is a MWE.  

Thanks for your help!

**Comment by fernandomayer** [comment]
Perhaps are you using the original [moderncv](http://www.ctan.org/tex-archive/macros/latex/contrib/moderncv) package?

Note that the files in my repo are from an older version of this original package because I wanted to keep some things that the updated version didn't allow me (see [README](../blob/master/README.md)). Also, in my files, I didn't made a `banking` theme.

When I run your code inside a folder containing my files, it doesn't work because the lack of the theme. When I run the code outside the folder with my files, LaTeX compiles using the original modernvc package (which I also have installed), and it works as expected (no errors), and that dotted line also doesn't show for me.

Looking at [this example](http://mirror.jmu.edu/pub/CTAN/macros/latex/contrib/moderncv/examples/template_banking_red.pdf) from the original modernvc package with the banking theme, it looks like that dotted line is supposed to show up when creating subsection (but I'm not sure because I've never used it).

Take a look in this example, and if you can't figure out what to do, maybe the best place to ask for some help in this particular case is the [modernvc launchpad page](https://answers.launchpad.net/moderncv).

Hope that helps.

**Comment by gvoysey** [comment]
You are correct, and wow did I file this in the wrong place.  Thanks for your patience, and for pointing me in the right direction!
